### ISSUE TITLE
Missing plugin

### ISSUE THREAD

**Issue by rummanz** [gyan000/EOSConnect#2]
It will be great if you can add  send to <device> context menu to pantheon-files.

**Comment by gyan000** [comment]
Hello,

Yes, I already though to that in the past but I did not know how to implement it.
After seeing your message I took some time and finally found out how to do that.
1. create [contractor](https://github.com/elementary/contractor) files for each device in the `~/.local/share/contractor `, when the Share plugin is activated, in order to display a "Send to {device_name]" into context menu of Files.
2. when option is selected, use `dbus-send` to send a dbus command to the app.

I already implemented step 1:
![send-to](http://www.ijaz.fr/share/pictures/eos_connect/screenshot/send-to.jpeg)

I'll try to implement the dbus part this week if I have enough time.

**Comment by gyan000** [comment]
Hi @altrgeek ,

You *should* now be able to send file(s) to a device using File's context menu.

**Comment by gyan000** [comment]
TODO: need to cleanup contractor user directory at startup.

**Comment by rummanz** [comment]
Thanks a lot for your quick support. Highly appreciate your effort on this project.
