### ISSUE TITLE
Willing to ship Android device

### ISSUE THREAD

**Issue by Hedronmx** [gyan000/EOSConnect#6]
I have an Nextbit Robin sitting on my shelf.

Are you willing to continue the development of this app if I ship you the phone?

**Comment by gyan000** [comment]
Hi @Hedronmx , 

Sorry for the very late reply.
Thanks a lot for your proposition but no, I won't be motivated enough to continue the development because I'm not interested anymore with Android. (for now..., perhaps it can changes in the future)
But, I saw that @hannesschulze forked this project, creating "[conecto](ttps://github.com/hannesschulze/conecto/tree/master)". It seems to work on a new UI interface. (see new-ui branch)
So, I think it's best to now follow this fork to see how it evolves.

Thanks

**Comment by Hedronmx** [comment]
I see, no problem! Thanks for your awesome work!
